# .goreleaser.yml
project_name: certauth

builds:
  - id: "certauth"
    main: "./main.go"
    binary: "certauth"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - # The image_owners template will use the user's DockerHub username (hesusruiz)
    # The image name will be certauth
    image_owners:
      - hesusruiz
    image_templates:
      - "{{ .Env.IMAGE_OWNER }}/certauth:{{ .Version }}"
      - "{{ .Env.IMAGE_OWNER }}/certauth:latest"
    dockerfile: Dockerfile
    use_buildx: true
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

archives:
  - id: default
    builds:
      - certauth
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}_SNAPSHOT__{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
